name: openmmnqe_plumed_custom
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  # Python toolchain
  - python=3.13.*
  - pytest
  - pip
  - setuptools
  - wheel
  - numpy
  - pandas
  - scipy
  - matplotlib
  - mdanalysis
  - sympy
  - rdkit
  - pymace
  - ase

  # OpenMM source-build prerequisites
  - cmake
  - make
  - cython
  - swig
  - doxygen

  # Practical build helpers
  - git
  - ninja
  - pkg-config

  # openmm-ml runtime/build-adjacent deps
  - cuda-toolkit
  - pytorch-gpu

  # Plumed
  - zlib
  - mkl
  - mkl-include
  - sysroot_linux-64
  - compilers
  - libblas
  - liblapack

  # downstream
  - openmmforcefields
  - pdbfixer