name: openmmnqe
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.*
  - pytorch-cuda=12.6
  - pytest
  - pandas
  - numpy
  - scipy
  - matplotlib
  - mdanalysis
  - sympy
  - pdbfixer
  - rdkit
  - pymace=0.3.15
  - ase=3.28.0
  - openmm=8.5.0
  - openmm-ml=1.6
  - openmm-plumed=2.1
  - openmmforcefields