name: openmmnqe

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.14.*
  - pip
  - pytest
  - pandas
  - matplotlib
  - mdanalysis
  - pdbfixer
  - "pytorch=*=cuda*"
  - pymace>=0.3.16
  - ase>=3.28.0
  - openmm>=8.5.1
  - openmm-ml>=1.6
  - openmm-plumed>=2.1
  - openmmforcefields

  - pip:
      - torch-dftd
      - git+https://github.com/LouieSlocombe/geodesic_interpolate.git