name: openmmnqe_custom
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - pip
  - pytest
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sympy
  - ase
  - pytorch
  - cmake
  - make
  - swig
  - cython
  - compilers
  - git
  - pybind11
  - doxygen
  - setuptools
  - ambertools
  - pdbfixer
  - rdkit
  - nnpops
  - pip:
      - mace-torch