name: openmmnqe_custom
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.13.*
  - pytest
  - pip
  - setuptools
  - wheel

  # Scientific Python Stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - mdanalysis
  - sympy
  - rdkit
  - pymace
  - ase

  # Build tools & compilers (Crucial for OpenMM/PLUMED)
  - compilers
  - cmake
  - make
  - ninja
  - cython
  - swig
  - doxygen
  - pkg-config
  - sysroot_linux-64

  # Math & Core Libraries
  - zlib
  - mkl
  - mkl-include
  - libblas
  - liblapack

  # downstream
  - openmmforcefields
  - pdbfixer

  - pip:
      - torch --index-url https://download.pytorch.org/whl/cpu
      - torchvision --index-url https://download.pytorch.org/whl/cpu