name: openmmnqe_custom
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - python=3.13.*
  - pytest
  - pip
  - setuptools
  - wheel

  # Scientific Python Stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - mdanalysis
  - sympy
  - rdkit
  - pymace
  - ase

  # Build tools & compilers (Crucial for OpenMM/PLUMED)
  - compilers
  - cmake
  - make
  - ninja
  - cython
  - swig
  - doxygen
  - pkg-config
  - sysroot_linux-64

  # Math & Core Libraries
  - zlib
  - mkl
  - mkl-include
  - libblas
  - liblapack

  # ML / GPU Stack
  - cuda-toolkit
  - pytorch
  - pytorch-gpu

  # downstream
  - openmmforcefields
  - pdbfixer