name: openmmnqe2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.*
  - pytorch-gpu
  - openmm=8.4
  - openmm-ml=1.5
  - openmm-plumed=2.1
  - pymace=0.3.15
  - pytest
  - pandas
  - matplotlib
  - mdanalysis
  - sympy
  - ase>=3.27.0
  - openmmforcefields
  - openmmtools
  - ambertools
  - pdbfixer
  - rdkit
  - nnpops