name: openmmnqe_custom
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # Python toolchain
  - python=3.13.*
  - pip
  - setuptools
  - wheel
  - numpy
  - pandas
  - scipy
  - matplotlib
  - mdanalysis
  - sympy
  - ambertools
  - rdkit
  - pymace=0.3.15
  - ase=3.27.0

  # OpenMM source-build prerequisites
  - cmake>=3.17
  - make
  - cython
  - swig
  - doxygen

  # Practical build helpers
  - git
  - ninja
  - pkg-config

  # openmm-ml runtime/build-adjacent deps
  - cuda-toolkit
  - pytorch-gpu

  # Nice to have for validation
  - pytest

#  - openmm-plumed=2.1
#  - openmmforcefields
#  - openmmtools
#  - pdbfixer